spring.application.name=employee-portal

# Jwt
app.jwt.secret=your-256-bit-secret-key-here
app.jwt.access-token-expiry=900000
app.jwt.refresh-token-expiry=604800000

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/employee_portal
spring.datasource.username=yourdbusername
spring.datasource.password=yourpassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server
server.port=8080